# Updated Dracula-themed yambar configuration with corrected volume display

bar:
  height: 35
  location: top
  spacing: 18
  margin: 8

  font: monospace:pixelsize=15
  foreground: f8f8f2FF
  background: 282a36FF

  border:
    width: 2
    color: 44475aFF
    margin: 7
    top-margin: 1

  left:
    - i3:
        content:
          "":
            map:
              conditions:
                state == focused:
                  string: {text: " {name}", foreground: bd93f9FF, margin: 7}
                state == unfocused:
                  string: {text: " {name}", foreground: f8f8f2FF, margin: 7}
                state == urgent:
                  string: {text: " {name}", foreground: e06c75FF, margin: 7}
                state == invisible:
                  string: {text: " {name}", foreground: 6272a4FF, margin: 7}
    - battery:
        name: BAT0 # Replace with your actual battery name, if different
        poll-interval: 1000
        content:
          list:
            items:
              - map:
                  conditions:
                    state == charging:
                      - string: {text: " {capacity}%", foreground: 8be9fdFF} # Icon and text for charging
                    state != charging:
                      - ramp:
                          tag: capacity
                          items:
                            - string: {text: " {capacity}%", foreground: ff5555FF}
                            - string: {text: " {capacity}%", foreground: ffb86cFF}
                            - string: {text: " {capacity}%", foreground: f1fa8cFF}
                            - string: {text: " {capacity}%", foreground: 50fa7bFF}
                            - string: {text: " {capacity}%", foreground: 8be9fdFF}
    - cpu:
       poll-interval: 750
       content:
         map:
          conditions:
            id == -1: # Aggregate CPU usage
              - ramp:
                  tag: cpu
                  items:
                    - string: {text: " ", foreground: 50fa7bFF} # Low usage - Green
                    - string: {text: " ", foreground: 8be9fdFF} # Light usage - Light Blue
                    - string: {text: " ", foreground: f1fa8cFF} # Moderate usage - Yellow
                    - string: {text: " ", foreground: ffb86cFF} # Medium usage - Orange
                    - string: {text: " ", foreground: ff79c6FF} # High usage - Pink
                    - string: {text: " ", foreground: bd93f9FF} # Very high usage - Purple
                    - string: {text: " ", foreground: ff5555FF} # Near full usage - Red
                    - string: {text: " ", foreground: ff0000FF} # Maximum usage - Dark Red
            id >= 0:
             - ramp:
                 tag: cpu
                 items:
                   - string: {text: "▁", foreground: 50fa7bFF} # Lowest usage - Green
                   - string: {text: "▂", foreground: 8be9fdFF} # Low usage - Light Blue
                   - string: {text: "▃", foreground: f1fa8cFF} # Moderate usage - Yellow
                   - string: {text: "▄", foreground: ffb86cFF} # Medium usage - Orange
                   - string: {text: "▅", foreground: ff79c6FF} # High usage - Pink
                   - string: {text: "▆", foreground: bd93f9FF} # Very high usage - Purple
                   - string: {text: "▇", foreground: ff5555FF} # Near full usage - Red
                   - string: {text: "█", foreground: ff0000FF} # Maximum usage - Dark Red
    - mem:
        poll-interval: 750
        content:
          list:
            items:
              - ramp:
                  tag: percent
                  items:
                    - string: {text: " {used:gb} GB", foreground: 50fa7bFF} # Lowest usage - Green
                    - string: {text: " {used:gb} GB", foreground: 8be9fdFF} # Low usage - Light Blue
                    - string: {text: " {used:gb} GB", foreground: f1fa8cFF} # Moderate usage - Yellow
                    - string: {text: " {used:gb} GB", foreground: ffb86cFF} # Medium usage - Orange
                    - string: {text: " {used:gb} GB", foreground: ff79c6FF} # High usage - Pink
                    - string: {text: " {used:gb} GB", foreground: bd93f9FF} # Very high usage - Purple
                    - string: {text: " {used:gb} GB", foreground: ff5555FF} # Near full usage - Red
                    - string: {text: " {used:gb} GB", foreground: ff0000FF} # Maximum usage - Dark Red
  center:
    - clock:
        time-format: "%-I:%M %p"
        date-format: "%b %d"
        content:
          - string: {text: " {date} {time}", foreground: bd93f9FF}

  right:
    - network: # Add network module to display the current network
        name: wlan0
        poll-interval: 750
        content:
          list:
            items:
              - map:
                  conditions:
                    state == up: # When network is connected
                      string: {text: " {ssid}  {dl-speed:mb}  {ul-speed:mb} MB/s", foreground: ff79c6ff}
                    state == down: # When network is disconnected
                      string: {text: "Disconnected", foreground: ff79c6ff} # Show a 'No Network' message
    - pipewire:
        content:
          list:
            items:
              - map:
                  conditions:
                    muted:
                      {string: {text: " ", foreground: ffb86cff}} # Muted
                    type == "sink":
                      - ramp:
                          tag: cubic_volume # Using percent tag for accurate volume representation
                          items:
                            - string: {text: " ", foreground: ffb86cff} # Low volume
                            - string: {text: " ", foreground: ffb86cff} # Medium volume
                            - string: {text: " ", foreground: ffb86cff} # High volume
                      - string: {text: "{cubic_volume}% ", foreground: ffb86cff}
