theme = "dracula"

[editor]
line-number = "relative"
color-modes = true
bufferline = "multiple"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true
